title:              Reptile Coding
email:              reptilecoding@hotmail.co.uk
description:        Blog by a professional software engineer
author:             Conor Watson

# Social Profiles
twitter_username:   reptileCoding
github_username:    moobywotsit
facebook_username:  Reptilecoding
linkedin_username:  moobywotsit

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
